#!/usr/bin/python3

import matplotlib.pyplot as plt
import sys
import random as rand 
 
dominant = rand.randint(0,5)

def read_argument():
    print("-----")
    for i in sys.argv[1:-1]:
        print(i)
    print("-----")

def read_real_time(fname):
    times = []
    with open(fname) as f:
        print(fname + " opened")
        content = f.readlines()
        for i in range(len(content)):
            if i % 4 == 1:
                strings = content[i][5::].split('m')
                value = int(strings[0])*60 + float(strings[1][:-2])
                times.append(value)
    return times

def pick_rgb():
    RGB = [0,0,0]
    V = [0,0,0]
    global dominant 
    dominant = (dominant + rand.randint(1,3)) % 6
    print ("DOMINANT: "+ str(dominant)) 
    V[0] = 221 #rand.randint(100,170)
    V[1] = rand.randint(124,221)
    V[2] = 124
    RGB[int(dominant/2)] = V[0]
    RGB[int(dominant/2+1)%3] = V[1]
    RGB[int(dominant/2+2)%3] = V[2]
    
    return '#{:02x}{:02x}{:02x}'.format(RGB[0],RGB[1],RGB[2])
    
#MAIN
f = plt.figure()
for i in sys.argv[1:-1]:
    print("trying to read in " + i)
    times = read_real_time(i)
    plt.plot(times, color=pick_rgb())
plt.ylabel('real time spent')
#plt.show()

f.savefig("foo.pdf", bbox_inches='tight')
