#!/usr/bin/python3

import matplotlib.pyplot as plt
import sys
import random as rand 

chosen_dominant = 0
#TODO Mix this list 
dominant_list = [0,1,3,4,5] 

def read_argument():
    print("-----")
    for i in sys.argv[1:-1]:
        print(i)
    print("-----")

def read_real_time(fname):
    times = []
    with open(fname) as f:
        print(fname + " opened")
        content = f.readlines()
        for i in range(len(content)):
            if i % 4 == 1:
                strings = content[i][5::].split('m')
                value = int(strings[0])*60 + float(strings[1][:-2])
                
                times.append(value)
    return times

def pick_rgb():
    RGB = [0,0,0]
    V = [0,0,0]
    global chosen_dominant
    global dominant_list 
    dominant = dominant_list[chosen_dominant]
    chosen_dominant =  (chosen_dominant +1)%5
    print ("DOMINANT: "+ str(dominant)) 
    V[0] = 221 
    if dominant % 2 == 1: 
        V[1] = rand.randint(200,221)
    else:
        V[1] = rand.randint(115,130)
    V[2] = 115
    RGB[int(dominant/2)] = V[0]
    RGB[int(dominant/2+1)%3] = V[1]
    RGB[int(dominant/2+2)%3] = V[2]
    print("COLOR: " ,RGB[0],RGB[1],RGB[2])   
    return '#{:02x}{:02x}{:02x}'.format(RGB[0],RGB[1],RGB[2])
    
#MAIN
f = plt.figure()
for i in sys.argv[1:-1]:
    print("trying to read in " + i)
    times = read_real_time(i)
    name = i.replace(".txt","")
    plt.plot(times, color=pick_rgb(), label=name)
    print("Graph name : ", name)
plt.ylabel('real time spent')
plt.legend(loc='upper left')
#plt.show()

f.savefig(sys.argv[-1], bbox_inches='tight')
